name: phasestim2022
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - numpy>=1.20.0
  - scipy>=1.7.0
  - matplotlib>=3.3.0
  - ipython>=7.0.0
  - nbformat>=5.0.0
  - pip
  - pip:
    - trodesnetwork==0.0.11
    - argparse